-- ============================================================================
-- Populate the gap draft scaffolds with the ACTUAL market products + prices
-- found in the PK sourcing research (docs/catalogue-gaps.csv): real name, brand,
-- and the observed market/retail reference price (integer PKR). Still
-- status='draft' (guarded in WHERE) — the owner confirms sourcing, sets their
-- own retail price (these are market refs, adjust for margin) and adds a product
-- image before publishing. seo_title/seo_description stay keyword-led.
-- Idempotent: plain UPDATEs keyed by slug + status='draft'.
-- ============================================================================

-- ── Supplements ──────────────────────────────────────────────────────────
update products set name='Nutrifactor Vitamin B12 500mcg', brand='Nutrifactor', price=990, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Vitamin B12 500mcg ~PKR 990 (nutrifactor.com.pk); imported Natural Factors 1000mcg sublingual ~PKR 4,250. See docs/catalogue-gaps.csv.' where slug='vitamin-b12' and status='draft';
update products set name='Nutrifactor Creatine Monohydrate 200g', brand='Nutrifactor', price=4990, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Creatine Monohydrate 200g ~PKR 4,990 (nutrifactor.com.pk); Jacked Nutrition micronised ~PKR 4,995. See docs/catalogue-gaps.csv.' where slug='creatine-monohydrate' and status='draft';
update products set name='Nutrifactor Melatonin 3mg', brand='Nutrifactor', price=850, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Melatonin 3mg ~PKR 850 (dvago.pk); 5mg ~PKR 990. See docs/catalogue-gaps.csv.' where slug='melatonin' and status='draft';
update products set name='Nutrifactor Yumcider ACV Gummies', brand='Nutrifactor', price=990, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Yumcider Apple Cider Vinegar gummies ~PKR 990 (nutrifactor.com.pk). See docs/catalogue-gaps.csv.' where slug='apple-cider-vinegar' and status='draft';
update products set name='Seven Seas Cod Liver Oil (120 caps)', brand='Seven Seas', price=7830, description='DRAFT — set your retail price & add an image, then publish. Market ref: Seven Seas Cod Liver Oil 120 capsules ~PKR 7,830 (sevenseas.com.pk). See docs/catalogue-gaps.csv.' where slug='cod-liver-oil' and status='draft';
update products set name='Nutrifactor Nuzinc (Zinc 50mg)', brand='Nutrifactor', price=950, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Nuzinc zinc gluconate 50mg ~PKR 950 (nutrifactor.com.pk). See docs/catalogue-gaps.csv.' where slug='zinc-supplement' and status='draft';
update products set name='Nutrifactor Ginseng 250mg', brand='Nutrifactor', price=990, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Ginseng 250 (Panax ginseng 250mg) ~PKR 990 (nutrifactor.com.pk). See docs/catalogue-gaps.csv.' where slug='ginseng' and status='draft';
update products set name='Nutrifactor Ginkgo Focus', brand='Nutrifactor', price=1150, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Ginkgo Focus (ginkgo biloba + ginseng) ~PKR 1,150 (nutrifactor.com.pk). See docs/catalogue-gaps.csv.' where slug='ginkgo-biloba' and status='draft';
update products set name='Nutrifactor E-Cell 400 (Vitamin E 400 IU)', brand='Nutrifactor', price=990, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor E-Cell 400 ~PKR 990 (myvitaminstore.pk); pharmacy Evion 400 ~PKR 180/strip. See docs/catalogue-gaps.csv.' where slug='vitamin-e' and status='draft';
update products set name='Natural Factors Acidophilus & Bifidus (Probiotic)', brand='Natural Factors', price=3990, description='DRAFT — set your retail price & add an image, then publish. Market ref: Natural Factors Acidophilus & Bifidus 5B CFU ~PKR 3,990 (vitaminshouse.com). See docs/catalogue-gaps.csv.' where slug='probiotics' and status='draft';
update products set name='Nutrifactor Qfactor (CoQ10 100mg)', brand='Nutrifactor', price=2500, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Qfactor CoQ10 100mg ~PKR 2,500 (nutrifactor.com.pk). See docs/catalogue-gaps.csv.' where slug='coq10' and status='draft';
update products set name='Nature''s Bounty Selenium 200mcg', brand='Nature''s Bounty', price=3495, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nature''s Bounty Selenium 200mcg, 100 tablets ~PKR 3,495 (myvitaminstore.pk). See docs/catalogue-gaps.csv.' where slug='selenium' and status='draft';
update products set name='Nutrifactor Femrose 500 (Evening Primrose Oil)', brand='Nutrifactor', price=1250, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Femrose 500 ~PKR 1,000-1,500 (dawaai.pk) — verify on page. See docs/catalogue-gaps.csv.' where slug='evening-primrose-oil' and status='draft';
update products set name='Nutrifactor B-50 Super B-Complex', brand='Nutrifactor', price=1150, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor B-50 B-Complex ~PKR 1,150 (nutrifactor.com.pk). See docs/catalogue-gaps.csv.' where slug='vitamin-b-complex' and status='draft';
update products set name='Kexinsh Raw Organic Sea Moss Capsules', brand=null, price=5500, description='DRAFT — set your retail price & add an image, then publish. Market ref: Kexinsh sea moss capsules ~PKR 5,500 (nifdo.com) — niche import / dropship, confirm stock. See docs/catalogue-gaps.csv.' where slug='sea-moss' and status='draft';
update products set name='Nutrifactor Whey Protein 400g', brand='Nutrifactor', price=6490, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Whey Protein 400g ~PKR 6,490 (was sold out at check); MuscleTech Nitro-Tech ~PKR 20,655. See docs/catalogue-gaps.csv.' where slug='whey-protein' and status='draft';
update products set name='Sunbeam Psyllium Husk (Ispaghol) 160g', brand='Sunbeam', price=1420, description='DRAFT — set your retail price & add an image, then publish. Market ref: Sunbeam Psyllium Husk 160g ~PKR 1,420 (50g ~480 / 100g ~955) (sunbeamfoods.com.pk). See docs/catalogue-gaps.csv.' where slug='psyllium-husk' and status='draft';
update products set name='VERSUS Marine Collagen (24 sachets)', brand='VERSUS', price=6400, description='DRAFT — set your retail price & add an image, then publish. Market ref: VERSUS hydrolysed Marine Collagen 10g x 24 ~PKR 6,400 (versusforher.com); NeoCell bovine ~PKR 8,495. See docs/catalogue-gaps.csv.' where slug='collagen-peptides-powder' and status='draft';
update products set name='Nutrifactor Normega 1000 (Omega-3 Fish Oil)', brand='Nutrifactor', price=1800, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nutrifactor Normega 1000 (180mg EPA/120mg DHA) ~PKR 1,800 (nutrifactor.com.pk). See docs/catalogue-gaps.csv.' where slug='omega-3-fish-oil' and status='draft';
update products set name='Nature''s Bounty Biotin 10,000mcg', brand='Nature''s Bounty', price=2750, description='DRAFT — set your retail price & add an image, then publish. Market ref: Nature''s Bounty Biotin 10000mcg ~PKR 2,750 (mybag.pk, varies widely — verify); local Nutrifactor Biotin Plus 2500mcg ~PKR 1,150. See docs/catalogue-gaps.csv.' where slug='biotin-10000-mcg' and status='draft';

-- ── Beauty / Hair ────────────────────────────────────────────────────────
update products set name='Saeed Ghani Black Kajal Pencil', brand='Saeed Ghani', price=150, description='DRAFT — set your retail price & add an image, then publish. Market ref: Saeed Ghani Kajal Pencil ~PKR 100-200 (saloni.pk); Rivaj UK kajal/eyeliner ~PKR 250-700. See docs/catalogue-gaps.csv.' where slug='kajal' and status='draft';
update products set name='Conatural Rosemary Essential Oil 10ml', brand='Conatural', price=1281, description='DRAFT — set your retail price & add an image, then publish. Market ref: Conatural Rosemary Essential Oil 10ml ~PKR 1,281 (conaturalintl.com). See docs/catalogue-gaps.csv.' where slug='rosemary-oil' and status='draft';
update products set name='Hemani Castor Oil 30ml', brand='Hemani', price=610, description='DRAFT — set your retail price & add an image, then publish. Market ref: Hemani Castor Oil 30ml ~PKR 610 (pk.hemaniherbals.com); 60ml ~PKR 310-335 (Naheed). See docs/catalogue-gaps.csv.' where slug='castor-oil' and status='draft';
update products set name='The Ordinary Salicylic Acid 2% Solution 30ml', brand='The Ordinary', price=3650, description='DRAFT — set your retail price & add an image, then publish. Market ref: The Ordinary Salicylic Acid 2% 30ml ~PKR 3,650 (theskinfit.com); Garnier BHA micellar ~PKR 600-900 (cheaper alt). See docs/catalogue-gaps.csv.' where slug='salicylic-acid-serum' and status='draft';
update products set name='The Ordinary Retinol 0.2% in Squalane 30ml', brand='The Ordinary', price=3590, description='DRAFT — set your retail price & add an image, then publish. Market ref: The Ordinary Retinol 0.2% in Squalane 30ml ~PKR 3,590 (ordinary.pk). See docs/catalogue-gaps.csv.' where slug='retinol-serum' and status='draft';
update products set name='Conatural Hyaluronic Acid 2% + B5 Serum 30ml', brand='Conatural', price=1465, description='DRAFT — set your retail price & add an image, then publish. Market ref: Conatural Hyaluronic Acid 2% + B5 30ml ~PKR 1,465 (conaturalintl.com) — far cheaper than The Ordinary HA ~PKR 3,650. See docs/catalogue-gaps.csv.' where slug='hyaluronic-acid-serum' and status='draft';
update products set name='Saeed Ghani Ultra Hydrating Lip Balm 15ml', brand='Saeed Ghani', price=350, description='DRAFT — set your retail price & add an image, then publish. Market ref: Saeed Ghani Ultra Hydrating Lip Balm 15ml ~PKR 350 (saeedghani.pk); Conatural ~PKR 499. See docs/catalogue-gaps.csv.' where slug='lip-balm' and status='draft';
update products set name='Saeed Ghani Hair Growth Water 120ml', brand='Saeed Ghani', price=480, description='DRAFT — set your retail price & add an image, then publish. Market ref: Saeed Ghani Hair Growth Water 120ml ~PKR 480 (saeedghani.pk); onion hair oil ~PKR 408. See docs/catalogue-gaps.csv.' where slug='hair-growth-oil' and status='draft';
update products set name='Minoxin Plus Minoxidil 5% 60ml', brand='Minoxin', price=850, description='DRAFT — set your retail price & add an image, then publish. Market ref: Minoxin Plus 5% ~PKR 800-900 (healthwire.pk / dvago.pk) — pharmacy item, confirm. See docs/catalogue-gaps.csv.' where slug='minoxidil' and status='draft';
update products set name='Rivaj UK Waterproof Eyeliner', brand='Rivaj UK', price=400, description='DRAFT — set your retail price & add an image, then publish. Market ref: Rivaj UK eyeliner ~PKR 250-700 (daraz.pk) — verify shade/price. See docs/catalogue-gaps.csv.' where slug='eyeliner' and status='draft';
update products set name='Garnier Micellar Cleansing Water 400ml', brand='Garnier', price=1394, description='DRAFT — set your retail price & add an image, then publish. Market ref: Garnier Micellar Water 400ml ~PKR 1,394 (vegas.pk); 100ml ~PKR 349 — verify. See docs/catalogue-gaps.csv.' where slug='micellar-water' and status='draft';
update products set name='Rivaj UK Volume Strength Mascara', brand='Rivaj UK', price=550, description='DRAFT — set your retail price & add an image, then publish. Market ref: Rivaj UK mascara ~PKR 435-695 (daraz.pk); Sweet Touch ~PKR 1,380+ — verify. See docs/catalogue-gaps.csv.' where slug='mascara' and status='draft';
update products set name='Rivaj UK Waterproof Lip Pencil', brand='Rivaj UK', price=200, description='DRAFT — set your retail price & add an image, then publish. Market ref: Rivaj UK lip pencil ~PKR 108-235 (naheed.pk) — verify shade/price. See docs/catalogue-gaps.csv.' where slug='lip-liner' and status='draft';
update products set name='Rivaj UK Makeup Fixer / Setting Spray 100ml', brand='Rivaj UK', price=494, description='DRAFT — set your retail price & add an image, then publish. Market ref: Rivaj UK Makeup Fixer 100ml ~PKR 494 (rios.pk); 180ml ~PKR 520-650. See docs/catalogue-gaps.csv.' where slug='setting-spray' and status='draft';
update products set name='Garnier Hydra Bomb Tissue Mask', brand='Garnier', price=400, description='DRAFT — set your retail price & add an image, then publish. Market ref: Garnier Hydra Bomb sheet mask ~PKR 300-500 (naheed.pk) — verify. See docs/catalogue-gaps.csv.' where slug='sheet-mask' and status='draft';
