-- ============================================================================
-- Admin Web Push: the admin PWA subscribes phones/desktops to push, and every
-- admin notification (new order, payment failed, low stock, new review,
-- return request — whatever inserts into admin_notifications) fans out to
-- those devices instantly. Emails stay as the durable record; push is the
-- "don't miss an order" channel.
--
-- Keys: VAPID keys + the webhook shared secret are generated by the app on
-- first use and live in push_config — a service-role-only single-row table
-- (RLS enabled, no policies), NOT env vars, so no dashboard setup is needed.
-- ============================================================================

create table if not exists public.push_config (
  id                boolean primary key default true check (id),
  vapid_public_key  text not null,
  vapid_private_key text not null,
  webhook_secret    text not null,
  fanout_url        text not null default 'https://www.yellowpink.pk/api/admin/push/fanout',
  created_at        timestamptz not null default now()
);
alter table public.push_config enable row level security;
-- No policies: service-role only. The private key must never be client-readable.

create table if not exists public.push_subscriptions (
  id           uuid primary key default gen_random_uuid(),
  endpoint     text not null unique,
  p256dh       text not null,
  auth         text not null,
  -- Display-only provenance: which staff member enabled it, on what device.
  staff_name   text,
  label        text,
  created_at   timestamptz not null default now(),
  last_used_at timestamptz
);
alter table public.push_subscriptions enable row level security;

-- ─── Fan-out trigger ─────────────────────────────────────────────────────────
-- admin_notifications rows are inserted by DB triggers (orders, reviews,
-- returns, stock), so the fan-out hooks there and covers every kind without
-- touching app flows. pg_net does the HTTP call; environments without the
-- extension (CI-from-scratch, local harness) skip silently, as does a
-- database whose push_config hasn't been initialised yet. Push must never
-- break the notification insert, so the call is wrapped.
create or replace function public.push_fanout_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cfg record;
begin
  select webhook_secret, fanout_url into cfg from push_config limit 1;
  if cfg.webhook_secret is null or cfg.fanout_url is null then
    return new;
  end if;
  if not exists (select 1 from pg_extension where extname = 'pg_net') then
    return new;
  end if;
  begin
    perform net.http_post(
      url := cfg.fanout_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-push-secret', cfg.webhook_secret
      ),
      body := jsonb_build_object(
        'kind', new.kind,
        'title', new.title,
        'body', new.body,
        'link', new.link
      )
    );
  exception when others then
    null;
  end;
  return new;
end $$;

drop trigger if exists admin_notifications_push_fanout on public.admin_notifications;
create trigger admin_notifications_push_fanout
  after insert on public.admin_notifications
  for each row execute function public.push_fanout_notify();
