-- ============================================================================
-- Draft product scaffolds for the REST of the catalogue gaps (collagen,
-- omega-3, biotin already created in _167). All status='draft' → excluded from
-- storefront, sitemap and feeds (anon RLS + builders filter to 'published').
-- Keyword-ready seo_title/seo_description so they are one publish-click away;
-- the owner sets a real price, stock, image and description first. Per-item
-- suggested product, local PK source and price live in docs/catalogue-gaps.csv.
-- price is required (no default) → 0 placeholder (a draft is never charged).
-- Idempotent: delete-by-slug (draft only) then insert.
-- ============================================================================

delete from products where status = 'draft' and slug in (
  'vitamin-b12','creatine-monohydrate','melatonin','apple-cider-vinegar','cod-liver-oil',
  'zinc-supplement','ginseng','ginkgo-biloba','vitamin-e','probiotics','coq10','selenium',
  'evening-primrose-oil','vitamin-b-complex','sea-moss','whey-protein','psyllium-husk',
  'kajal','rosemary-oil','castor-oil','salicylic-acid-serum','retinol-serum',
  'hyaluronic-acid-serum','lip-balm','hair-growth-oil','minoxidil','eyeliner',
  'micellar-water','mascara','lip-liner','setting-spray','sheet-mask'
);

insert into products (name, slug, price, stock, category, status, track_inventory, seo_title, seo_description, description) values
-- ── Supplements ──────────────────────────────────────────────────────────
('Vitamin B12','vitamin-b12',0,0,'Immunity','draft',false,'Buy Vitamin B12 in Pakistan','Shop vitamin B12 (methylcobalamin) in Pakistan for energy and nerve health. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. Suggested product, local source & price: see docs/catalogue-gaps.csv. Set price/stock/image, then publish.'),
('Creatine Monohydrate','creatine-monohydrate',0,0,'Men''s Health','draft',false,'Buy Creatine Monohydrate in Pakistan','Shop micronised creatine monohydrate in Pakistan for strength and performance. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Melatonin','melatonin',0,0,'Immunity','draft',false,'Buy Melatonin in Pakistan — Sleep Support','Shop melatonin 3–5mg in Pakistan for better sleep. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Apple Cider Vinegar','apple-cider-vinegar',0,0,'Digestive & Gut','draft',false,'Buy Apple Cider Vinegar in Pakistan','Shop apple cider vinegar gummies and capsules in Pakistan for gut and metabolism support. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Cod Liver Oil','cod-liver-oil',0,0,'Heart Health','draft',false,'Buy Cod Liver Oil in Pakistan','Shop cod liver oil capsules in Pakistan — omega-3 plus vitamins A and D. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Zinc Supplement','zinc-supplement',0,0,'Immunity','draft',false,'Buy Zinc Supplement in Pakistan','Shop zinc tablets in Pakistan for immunity and skin health. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Ginseng','ginseng',0,0,'Immunity','draft',false,'Buy Ginseng in Pakistan','Shop Panax ginseng capsules in Pakistan for energy and vitality. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Ginkgo Biloba','ginkgo-biloba',0,0,'Immunity','draft',false,'Buy Ginkgo Biloba in Pakistan','Shop ginkgo biloba in Pakistan for memory and focus support. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Vitamin E','vitamin-e',0,0,'Immunity','draft',false,'Buy Vitamin E in Pakistan','Shop vitamin E 400 IU capsules in Pakistan for skin and antioxidant support. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Probiotics','probiotics',0,0,'Digestive & Gut','draft',false,'Buy Probiotics in Pakistan','Shop probiotic capsules in Pakistan for gut and digestive health. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('CoQ10','coq10',0,0,'Heart Health','draft',false,'Buy CoQ10 in Pakistan','Shop CoQ10 100mg in Pakistan for heart health and energy. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Selenium','selenium',0,0,'Immunity','draft',false,'Buy Selenium in Pakistan','Shop selenium 200mcg in Pakistan for thyroid and antioxidant support. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Evening Primrose Oil','evening-primrose-oil',0,0,'Women''s Health','draft',false,'Buy Evening Primrose Oil in Pakistan','Shop evening primrose oil in Pakistan for hormonal and skin support. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Vitamin B-Complex','vitamin-b-complex',0,0,'Immunity','draft',false,'Buy Vitamin B-Complex in Pakistan','Shop vitamin B-complex in Pakistan for energy and nervous-system support. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Sea Moss','sea-moss',0,0,'Immunity','draft',false,'Buy Sea Moss in Pakistan','Shop sea moss capsules in Pakistan — mineral-rich wellness support. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Whey Protein','whey-protein',0,0,'Men''s Health','draft',false,'Buy Whey Protein in Pakistan','Shop whey protein powder in Pakistan for muscle and recovery. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Psyllium Husk','psyllium-husk',0,0,'Digestive & Gut','draft',false,'Buy Psyllium Husk (Ispaghol) in Pakistan','Shop psyllium husk / ispaghol in Pakistan for fibre and digestive health. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
-- ── Beauty / Hair ────────────────────────────────────────────────────────
('Kajal','kajal',0,0,'Eyes','draft',false,'Buy Kajal in Pakistan','Shop smudge-proof black kajal in Pakistan for bold, defined eyes. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Rosemary Oil','rosemary-oil',0,0,'Hair Care','draft',false,'Buy Rosemary Oil for Hair in Pakistan','Shop rosemary oil in Pakistan for hair growth and a healthy scalp. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Castor Oil','castor-oil',0,0,'Hair Care','draft',false,'Buy Castor Oil in Pakistan','Shop pure castor oil in Pakistan for hair, lashes and brows. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Salicylic Acid Serum','salicylic-acid-serum',0,0,'Cleansers & Treatments','draft',false,'Buy Salicylic Acid (BHA) in Pakistan','Shop salicylic acid 2% BHA in Pakistan for acne and clogged pores. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Retinol Serum','retinol-serum',0,0,'Cleansers & Treatments','draft',false,'Buy Retinol Serum in Pakistan','Shop retinol serum in Pakistan for fine lines and skin renewal. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Hyaluronic Acid Serum','hyaluronic-acid-serum',0,0,'Cleansers & Treatments','draft',false,'Buy Hyaluronic Acid Serum in Pakistan','Shop hyaluronic acid serum in Pakistan for deep hydration and plump skin. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Lip Balm','lip-balm',0,0,'Lip & Cheek Tints','draft',false,'Buy Lip Balm in Pakistan','Shop hydrating lip balm in Pakistan for soft, nourished lips. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Hair Growth Oil','hair-growth-oil',0,0,'Hair Care','draft',false,'Buy Hair Growth Oil in Pakistan','Shop hair growth oil and serum in Pakistan for thicker, stronger hair. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Minoxidil 5%','minoxidil',0,0,'Hair Care','draft',false,'Buy Minoxidil 5% in Pakistan','Shop minoxidil 5% in Pakistan for hair regrowth. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Eyeliner','eyeliner',0,0,'Eyes','draft',false,'Buy Eyeliner in Pakistan','Shop liquid and pencil eyeliner in Pakistan for sharp, defined eyes. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Micellar Water','micellar-water',0,0,'Cleansers & Treatments','draft',false,'Buy Micellar Water in Pakistan','Shop micellar cleansing water in Pakistan to remove makeup gently. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Mascara','mascara',0,0,'Eyes','draft',false,'Buy Mascara in Pakistan','Shop volumising and lengthening mascara in Pakistan. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Lip Liner','lip-liner',0,0,'Lip & Cheek Tints','draft',false,'Buy Lip Liner in Pakistan','Shop long-lasting waterproof lip liner in Pakistan in multiple shades. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Setting Spray','setting-spray',0,0,'Face Makeup','draft',false,'Buy Makeup Setting Spray in Pakistan','Shop makeup setting spray and fixer in Pakistan for long-wear makeup. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.'),
('Sheet Mask','sheet-mask',0,0,'Cleansers & Treatments','draft',false,'Buy Sheet Masks in Pakistan','Shop hydrating sheet masks in Pakistan for an instant glow. Authentic, with cash on delivery nationwide.','DRAFT — pending sourcing. See docs/catalogue-gaps.csv for suggested product, local source & price. Set price/stock/image, then publish.');
